const BubbleTeam = () => {
  return (
    <svg
      width="1075"
      height="538"
      viewBox="0 0 1075 538"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <circle cx="47.5" cy="339.5" r="38.5" fill="#125E9C" />
      <circle
        cx="1022.5"
        cy="210.5"
        r="37.5"
        fill="url(#pattern0)"
        stroke="#50B0E2"
        strokeWidth="2"
      />
      <circle
        cx="57"
        cy="241"
        r="33"
        fill="url(#pattern1)"
        stroke="#DA3D16"
        strokeWidth="2"
      />
      <circle
        cx="1013.5"
        cy="310.5"
        r="32.5"
        fill="url(#pattern2)"
        stroke="#00A973"
        strokeWidth="2"
      />
      <circle cx="336.5" cy="231.5" r="33.5" fill="#50B0E2" />
      <circle
        cx="733.5"
        cy="320.5"
        r="32.5"
        fill="url(#pattern3)"
        stroke="#50B0E2"
        strokeWidth="2"
      />
      <circle
        cx="531.5"
        cy="444.5"
        r="32.5"
        fill="url(#pattern4)"
        stroke="#CA951E"
        strokeWidth="2"
      />
      <circle
        cx="566"
        cy="342"
        r="33"
        fill="url(#pattern5)"
        stroke="#00A973"
        strokeWidth="2"
      />
      <circle
        cx="583"
        cy="227"
        r="33"
        fill="url(#pattern6)"
        stroke="#DA3D16"
        strokeWidth="2"
      />
      <ellipse
        cx="538.5"
        cy="106.5"
        rx="33.5"
        ry="33.5"
        transform="rotate(-180 538.5 106.5)"
        fill="#DA3D16"
      />
      <circle cx="132" cy="187" r="34" fill="#CA951E" />
      <ellipse
        cx="938"
        cy="365"
        rx="34"
        ry="34"
        transform="rotate(-180 938 365)"
        fill="#DA3D16"
      />
      <ellipse
        cx="152.5"
        cy="88.5"
        rx="33.5"
        ry="33.5"
        transform="rotate(-180 152.5 88.5)"
        fill="#DA3D16"
      />
      <ellipse cx="142.5" cy="401" rx="34.5" ry="34" fill="#E50064" />
      <circle
        cx="927.5"
        cy="151.5"
        r="33.5"
        fill="url(#pattern7)"
        stroke="#00A973"
        strokeWidth="2"
      />
      <circle
        cx="328.5"
        cy="445.5"
        r="33.5"
        fill="url(#pattern8)"
        stroke="#CA951E"
        strokeWidth="2"
      />
      <ellipse
        cx="741.5"
        cy="106.5"
        rx="34.5"
        ry="33.5"
        transform="rotate(-180 741.5 106.5)"
        fill="#00A973"
      />
      <circle cx="237" cy="450" r="34" fill="#EBEAF1" />
      <circle
        cx="57"
        cy="437"
        r="33"
        fill="url(#pattern9)"
        stroke="#50B0E2"
        strokeWidth="2"
      />
      <circle cx="59" cy="176" r="13" fill="#4A2870" />
      <ellipse
        cx="1011"
        cy="376"
        rx="13"
        ry="13"
        transform="rotate(-180 1011 376)"
        fill="#4A2870"
      />
      <ellipse
        cx="549.5"
        cy="20.5"
        rx="8.5"
        ry="8.5"
        transform="rotate(-180 549.5 20.5)"
        fill="#4A2870"
      />
      <ellipse
        cx="511"
        cy="190"
        rx="13"
        ry="13"
        transform="rotate(-180 511 190)"
        fill="#EBEAF1"
      />
      <circle cx="9" cy="412" r="9" fill="#EBEAF1" />
      <ellipse
        cx="1065"
        cy="153"
        rx="10"
        ry="10"
        transform="rotate(-180 1065 153)"
        fill="#00A973"
      />
      <circle cx="193.5" cy="163.5" r="8.5" fill="#EBEAF1" />
      <ellipse
        cx="877"
        cy="388"
        rx="9"
        ry="9"
        transform="rotate(-180 877 388)"
        fill="#50B0E2"
      />
      <ellipse
        cx="497.5"
        cy="363"
        rx="8.5"
        ry="9"
        transform="rotate(-180 497.5 363)"
        fill="#50B0E2"
      />
      <ellipse cx="333.5" cy="376" rx="9.5" ry="9" fill="#EBEAF1" />
      <ellipse
        cx="736.5"
        cy="175.5"
        rx="9.5"
        ry="9.5"
        transform="rotate(-180 736.5 175.5)"
        fill="#EBEAF1"
      />
      <circle cx="223" cy="521" r="13" fill="#4A2870" />
      <ellipse
        cx="847"
        cy="13"
        rx="13"
        ry="13"
        transform="rotate(-180 847 13)"
        fill="#DA3D16"
      />
      <ellipse
        cx="333"
        cy="54"
        rx="13"
        ry="13"
        transform="rotate(-180 333 54)"
        fill="#DA3D16"
      />
      <ellipse
        cx="689.5"
        cy="19.5"
        rx="10.5"
        ry="10.5"
        transform="rotate(-180 689.5 19.5)"
        fill="#E50064"
      />
      <circle cx="409.5" cy="252.5" r="13.5" fill="#125E9C" />
      <ellipse
        cx="645"
        cy="308"
        rx="24"
        ry="24"
        transform="rotate(-180 645 308)"
        fill="#4A2870"
      />
      <ellipse
        cx="732.5"
        cy="494.5"
        rx="13.5"
        ry="13.5"
        transform="rotate(-180 732.5 494.5)"
        fill="#E50064"
      />
      <circle
        cx="144"
        cy="295"
        r="47"
        fill="url(#pattern10)"
        stroke="#4A2870"
        strokeWidth="2"
      />
      <ellipse
        cx="924.952"
        cy="256.5"
        rx="50.0479"
        ry="48.5"
        transform="rotate(-180 924.952 256.5)"
        fill="#E50064"
      />
      <ellipse
        cx="488"
        cy="278"
        rx="47"
        ry="47"
        transform="rotate(-180 488 278)"
        fill="#E50064"
      />
      <circle
        cx="236.5"
        cy="238.5"
        r="39.5"
        fill="url(#pattern11)"
        stroke="#00A973"
        strokeWidth="2"
      />
      <circle
        cx="832.5"
        cy="314.5"
        r="38.5"
        fill="url(#pattern12)"
        stroke="#4A2870"
        strokeWidth="2"
      />
      <circle
        cx="373"
        cy="318"
        r="39"
        fill="url(#pattern13)"
        stroke="#4A2870"
        strokeWidth="2"
      />
      <ellipse
        cx="697"
        cy="234"
        rx="40"
        ry="40"
        transform="rotate(-180 697 234)"
        fill="#CA951E"
      />
      <circle
        cx="147"
        cy="499"
        r="38"
        fill="url(#pattern14)"
        stroke="#00A973"
        strokeWidth="2"
      />
      <circle
        cx="257"
        cy="341"
        r="49"
        fill="url(#pattern15)"
        stroke="#E50064"
        strokeWidth="2"
      />
      <circle
        cx="421"
        cy="126"
        r="61"
        fill="url(#pattern16)"
        stroke="#50B0E2"
        strokeWidth="2"
      />
      <circle
        cx="649"
        cy="425"
        r="61"
        fill="url(#pattern17)"
        stroke="#006B65"
        strokeWidth="2"
      />
      <ellipse
        cx="792"
        cy="422"
        rx="50"
        ry="50"
        transform="rotate(-180 792 422)"
        fill="#00A973"
      />
      <circle cx="439" cy="417" r="50" fill="#DA3D16" />
      <g filter="url(#filter0_d_891_1876)">
        <circle cx="277" cy="130" r="50" fill="url(#pattern18)" />
        <circle cx="277" cy="130" r="49" stroke="#4A2870" strokeWidth="2" />
      </g>
      <circle
        cx="632"
        cy="134"
        r="50"
        fill="url(#pattern19)"
        stroke="#E50064"
        strokeWidth="2"
      />
      <circle
        cx="923"
        cy="56"
        r="38"
        fill="url(#pattern20)"
        stroke="#DA3D16"
        strokeWidth="2"
      />
      <circle
        cx="837.5"
        cy="105.5"
        r="32.5"
        fill="url(#pattern21)"
        stroke="#CA951E"
        strokeWidth="2"
      />
      <g filter="url(#filter1_b_891_1876)">
        <circle cx="814" cy="212" r="49" fill="url(#pattern22)" />
        <circle cx="814" cy="212" r="48" stroke="#50B0E2" strokeWidth="2" />
      </g>
      <circle
        cx="1014"
        cy="116"
        r="31"
        fill="url(#pattern23)"
        stroke="#4A2870"
        strokeWidth="2"
      />
      <defs>
        <pattern
          id="pattern0"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern1"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern2"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern3"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern4"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern5"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern6"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern7"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern8"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern9"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern10"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern11"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern12"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern13"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern14"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern15"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern16"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern17"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <filter
          id="filter0_d_891_1876"
          x="223"
          y="80"
          width="108"
          height="108"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset dy="4" />
          <feGaussianBlur stdDeviation="2" />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"
          />
          <feBlend
            mode="saturation"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_891_1876"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_891_1876"
            result="shape"
          />
        </filter>
        <pattern
          id="pattern18"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern19"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern20"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern21"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <filter
          id="filter1_b_891_1876"
          x="761"
          y="159"
          width="106"
          height="106"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feGaussianBlur in="BackgroundImageFix" stdDeviation="2" />
          <feComposite
            in2="SourceAlpha"
            operator="in"
            result="effect1_backgroundBlur_891_1876"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_backgroundBlur_891_1876"
            result="shape"
          />
        </filter>
        <pattern
          id="pattern22"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
        <pattern
          id="pattern23"
          patternContentUnits="objectBoundingBox"
          width="1"
          height="1"
        ></pattern>
      </defs>
    </svg>
  );
};

export default BubbleTeam;
